config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "foods#index"
  resources :users
  resources :foods
  get 'general_shopping_list', to: 'general_shopping_list#index'
  get 'general_shopping_list' => 'general_shopping_list#index', as: 'shopping_list'


  resources :recipes
  get 'public_recipes' => 'recipes#public_recipes'

  get 'public_recipes' => 'recipes#public_recipes'
  get 'recipes/:id/add_ingredient' => 'recipe_foods#new', as:'add_recipe_food'
  resources :recipes
  # for updating the public 
  patch 'recipes/:id/toggle_public', to: 'recipes#toggle_public', as: 'toggle_public_recipe'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'recipe_foods' => 'recipe_foods#index', as:'recipe_foods'
  get 'recipe_foods/delete/:id' => 'recipe_foods#destroy', as: 'delete_recipe_food'
  post 'recipe_foods/create' => 'recipe_foods#create', as:'create_recipe_food'

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods

  validates :name, presence: true
  validates :preparation, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :cookingtime, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :description, presence: true
  validates :public, inclusion: { in: [true, false] }
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: %i[show public_recipes]

  def index
    @recipes = current_user.recipes.includes(:recipe_foods)
  end

  def show
    @recipe = Recipe.includes(recipe_foods: :food).find(params[:id])
    @recipe_foods = @recipe.recipe_foods
    @food = Food.all
  end

  def public_recipes
    @recipes = Recipe.includes(recipe_foods: :food).where(public: true).order(created_at: :desc)
    @recipe_foods = RecipeFood.includes(:food).all
  end

  def new
    @recipe = Recipe.new
  end

  def toggle_public
    @recipe = Recipe.find(params[:id])
    @recipe.update(public: !@recipe.public)

    redirect_to recipe_path(@recipe)
  end

  # POST /recipes
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy!

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation, :cookingtime, :description,
                                   :public).merge(user_id: current_user.id)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-outline mb-4">
    <%= form.label :name, class: "mb-2", style: "display: block" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-outline mb-4">
    <%= form.label :preparation, class: "mb-2", style: "display: block" %>
    <%= form.text_field :preparation, class: "form-control" %>
  </div>

  <div class="form-outline mb-4">
    <%= form.label :cookingtime, class: "mb-2", style: "display: block" %>
    <%= form.text_field :cookingtime, class: "form-control" %>
  </div>

  <div class="form-outline mb-4">
    <%= form.label :description, class: "mb-2", style: "display: block" %>
    <%= form.text_area :description, class: "form-control", style: "height: 10rem" %>
  </div>

  <div class="form-outline mb-4">
    <%= form.label :public, class: "mb-2", style: "display: block" %>
    <%= form.check_box :public %>
  </div>

  <div class="form-outline mb-4">
    <%= form.submit class: "btn btn-primary btn-block mb-3 w-10" %>
  </div>

<% end %>

app/views/recipes/_public_btn.html.erb
<%= form_with(model: @recipe, url: toggle_public_recipe_path(@recipe), method: :patch) do |form| %>
    <%= form.submit(@recipe.public? ? 'Make Private' : 'Make Public', class: 'btn btn-primary') %>
<% end %>
  

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>">
  <div class="d-flex justify-content-between">
    <%= content_tag :p, recipe.name, class: "fs-3" %>
    <%= render "recipes/public_btn" %>
  </div>

  <p>
    <strong>Preparation time:</strong>
    <%= recipe.preparation %>
  </p>

  <p>
    <strong>Cook time:</strong>
    <%= recipe.cookingtime %>
  </p>

  <p class="mb-3">
    <strong>User:</strong>
    <%= recipe.user_id %>
  </p>

</div>

app/views/recipes/_recipes.html.erb
<table class="table table-borderless pt-3">
  <tbody class="border border-primary-subtle">
    <tr>
      <td><%= link_to recipe.name, recipe %></td>
      <td colspan="3"><%= recipe.description %></td>
    </tr>
    <tr>
    <td>
    </td>
    </tr>
    <tr>
      <td><%= button_to "Remove", recipe, method: :delete, class: "fs-6 btn btn-primary me-4 mb-4" %></td>
      </tr>
  </tbody>
</table>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/index.html.erb
<p style="color: green" style="margin: 0 20%;"><%= notice %></p>
<p style="color: green"><%= notice %></p>

<h1 class="mb-5 text-center" style="margin-top: -2.5rem">Recipes</h1>

<div class="tab-content d-flex justify-content-center">
  <div class="tab-pane fade show active border rounded p-5" style="width: 57%" id="pills-login" role="tabpanel" aria-labelledby="tab-login">
  
    <div class="d-flex justify-content-end">
      <%= link_to "Add new Recipe", new_recipe_path, class: "fs-6 btn btn-primary me-4 mb-4" %>
    </div>

    <div id="recipes">
      <% @recipes.each do |recipe| %>
        <%= render 'recipes', recipe: recipe %>
      <% end %>
    </div>

  </div>
</div>

app/views/recipes/new.html.erb
<h1 class="mb-5 text-center" style="margin-top: -2.5rem">New Recipe</h1>

<div class="tab-content d-flex justify-content-center">
  <div class="tab-pane fade show active border rounded p-5" style="width: 57%" id="pills-login" role="tabpanel" aria-labelledby="tab-login">

    <%= render "form", recipe: @recipe %>
    <br>

    <div>
      <%= link_to "Back to recipes", recipes_path %>
    </div>
    
  </div>
</div>

app/views/recipes/public_recipes.html.erb
<h1 class="mb-5 text-center" style="margin-top: -2.5rem">Public Recipes</h1>

<div class="tab-content d-flex justify-content-center">
<div class="tab-pane fade show active border rounded p-5" style="width: 57%" id="pills-login" role="tabpanel" aria-labelledby="tab-login">
<table class="table table-borderless pt-3">
<% @recipes.each do |recipe| %>
  <% @ingredients = @recipe_foods.where(recipe_id: recipe.id) %>
  <% @total_price = 0 %>
  <% @ingredients.each do |item| %>
    <% @total_price += item.food.price * item.quantity %>
    <% end %>
    <tbody class="border border-primary-subtle public-recipe">
    <tr class="t2">
      <td><h4><%= link_to recipe.name, recipe %></h4></td>
      <td><%= recipe.description %></span></td>
    </tr>

    <tr class="t2">
      <td>By: <strong><%= recipe.user.name %></strong></td>
      <td><strong>The total price: $<%= @total_price %></strong></td>
    </tr>

    </tbody>
    <% end %>
</table>
  </div>
  </div>

app/views/recipes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= link_to "Back to recipes", recipes_path %>
<h1>Recipe</h1>

<h1 class="mb-5 text-center">Recipe Details</h1>
<div class="tab-content d-flex justify-content-center">
  <div class="tab-pane fade show active border rounded p-5" style="width: 57%" id="pills-login" role="tabpanel" aria-labelledby="tab-login">

    <%= render @recipe %>
    <div class="d-flex justify-content-between">
      <%= link_to "Generate Shopping List", shopping_list_path, class: "btn btn-primary" %>
      <% if current_user == @recipe.user %>
        <%= link_to "Add Ingredients", add_recipe_food_path, class: 'btn btn-primary' %>
      <% end %>
    </div>
    <hr>
    <div>

      <div id="recipes">
        <table id='foods_table' class="table">
          <thead class="thead-light">
            <tr>
              <th scope="col">Name</th>
              <th scope="col">Quantity</th>
              <th scope="col">Value</th>
              <th scope="col">Action</th>
            </tr>
          </thead>
          <tbody>
            <% @recipe_foods.each do |recipe_food| %>
              <% food_item = @food.find { |food| food.id == recipe_food.food_id } %>
              <tr>
                <td><%= food_item.name%></td>
                <td><%= recipe_food.quantity%></td>
                <td>$ <%= recipe_food.quantity * food_item.price %></td>
                <td><%= link_to "Delete", delete_recipe_food_path(recipe_food.id) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>