config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "foods#index"
  resources :users
  resources :foods
  get 'general_shopping_list', to: 'general_shopping_list#index'
  get 'general_shopping_list' => 'general_shopping_list#index', as: 'shopping_list'


  resources :recipes
  get 'public_recipes' => 'recipes#public_recipes'

  get 'public_recipes' => 'recipes#public_recipes'
  get 'recipes/:id/add_ingredient' => 'recipe_foods#new', as:'add_recipe_food'
  resources :recipes
  # for updating the public 
  patch 'recipes/:id/toggle_public', to: 'recipes#toggle_public', as: 'toggle_public_recipe'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'recipe_foods' => 'recipe_foods#index', as:'recipe_foods'
  get 'recipe_foods/delete/:id' => 'recipe_foods#destroy', as: 'delete_recipe_food'
  post 'recipe_foods/create' => 'recipe_foods#create', as:'create_recipe_food'

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy

  validates :name, presence: true, length: { maximum: 250 }
  validates :measurements, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_food, only: %i[show edit update destroy]

  # GET /foods or /foods.json
  def index
    @foods = Food.includes(:user).where(user_id: current_user.id).order(created_at: :asc)
  end

  # GET /foods/1 or /foods/1.json
  def show; end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit; end

  # POST /foods or /foods.json
  def create
    @food = current_user.foods.build(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to food_url(@food), notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1 or /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to food_url(@food), notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :measurements, :price, :quantity).merge(user_id: current_user.id)
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_food.html.erb
<!-- _food.html.erb -->
<tbody>
  <tr class="food-details">
    <td class="food-name"><%= food.name %></td>
    <td class="food-measurements"><%= food.measurements %></td>
    <td class="food-price"><%= food.price %></td>
  </tr>
</tbody>

app/views/foods/_form.html.erb
<%= form_with(model: food) do |form| %>
  <% if food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :measurements, style: "display: block" %>
    <%= form.text_field :measurements %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing food</h1>
<div class="container">

</div>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Show this food", @food %> |
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/index.html.erb
<div class="food-list">
  <%= link_to "New food", new_food_path, class: "float-right btn btn-primary" %>

  <% if @foods.present? %>
    <table id="food-list" class="table">
      <thead>
        <tr>
          <th>Food</th>
          <th>Measurements</th>
          <th>Unit Price</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @foods.each do |food| %>
          <tr>
            <td><%= food.name %></td>
            <td><%= food.measurements %></td>
            <td><%= food.price %></td>
            <td>
              <%= button_to "Delete", food, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p class="text-center">No items in the Food list</p>
  <% end %>
</div>

app/views/foods/new.html.erb
<h1>New food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @food %>

<div>
  <%= link_to "Edit this food", edit_food_path(@food) %> |
  <%= link_to "Back to foods", foods_path %>

  <%= button_to "Destroy this food", @food, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
</div>