config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "foods#index"
  resources :users
  resources :foods
  get 'general_shopping_list', to: 'general_shopping_list#index'
  get 'general_shopping_list' => 'general_shopping_list#index', as: 'shopping_list'


  resources :recipes
  get 'public_recipes' => 'recipes#public_recipes'

  get 'public_recipes' => 'recipes#public_recipes'
  get 'recipes/:id/add_ingredient' => 'recipe_foods#new', as:'add_recipe_food'
  resources :recipes
  # for updating the public 
  patch 'recipes/:id/toggle_public', to: 'recipes#toggle_public', as: 'toggle_public_recipe'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'recipe_foods' => 'recipe_foods#index', as:'recipe_foods'
  get 'recipe_foods/delete/:id' => 'recipe_foods#destroy', as: 'delete_recipe_food'
  post 'recipe_foods/create' => 'recipe_foods#create', as:'create_recipe_food'

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto px-4">
      <li class="nav-item active">
        <%= link_to "Foods", root_path, class:"navbar-brand fs-6" %>
      </li>
      <li class="nav-item">
         <%= link_to "Recipes", recipes_path, class:"navbar-brand fs-6" %>
      </li>
      <li class="nav-item">
        <%= link_to "Public Recipes", public_recipes_path, class:"navbar-brand fs-6" %>
      </li>
      <li class="nav-item">
        <%= link_to "Shopping List", general_shopping_list_path, class:"navbar-brand fs-6" %> <!-- Updated link -->
      </li>
    </ul>
    </div>
    <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: "fs-6 btn btn-primary me-4" %>
</nav>

app/views/layouts/_navbar_login.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light px-3">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto px-4">
      <li class="nav-item">
        <%= link_to "Public Recipes", public_recipes_path, class:"navbar-brand fs-6" %>
      </li>
    </ul>
    </div>
    <%= link_to 'Sign up', new_user_registration_path, class: "fs-6 btn btn-primary me-4" %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodRecipe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <% if user_signed_in? %>
    <%= render "layouts/navbar" %>
  <% else %>
    <%= render "layouts/navbar_login" %>
  <% end %>
  <h1 class="heading">Welcome To our Food App</h1>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>